export const redHoodAnimation = {
    "idle": {
        "frameCount": 2,
        "frameDelay": 12,
        "offsetX": 0,
        "offsetY": 0,
        "widthInFrame": 32,
        "heightInFrame": 32,
    },
    "hideHead": {
        "frameCount": 2,
        "frameDelay": 30,
        "offsetX": 0,
        "offsetY": 32,
        "widthInFrame": 32,
        "heightInFrame": 32,
    },
    "walk": {
        "frameCount": 4,
        "frameDelay": 10,
        "offsetX": 0,
        "offsetY": 64,
        "widthInFrame": 32,
        "heightInFrame": 32,
    },
    "run": {
        "frameCount": 8,
        "frameDelay": 4,
        "offsetX": 0,
        "offsetY": 96,
        "widthInFrame": 32,
        "heightInFrame": 32,
    },
    "duck": {
        "frameCount": 6,
        "frameDelay": 10,
        "offsetX": 0,
        "offsetY": 128,
        "widthInFrame": 32,
        "heightInFrame": 32,
    },
    "jump": {
        "frameCount": 8,
        "frameDelay": 7,
        "offsetX": 0,
        "offsetY": 160,
        "widthInFrame": 32,
        "heightInFrame": 32,
    },
    "disappear": {
        "frameCount": 3,
        "frameDelay": 10,
        "offsetX": 0,
        "offsetY": 192,
        "widthInFrame": 32,
        "heightInFrame": 32,
    },
    "dead": {
        "frameCount": 8,
        "frameDelay": 6,
        "offsetX": 0,
        "offsetY": 224,
        "widthInFrame": 32,
        "heightInFrame": 32,
    },
    "attack": {
        "frameCount": 8,
        "frameDelay": 6,
        "offsetX": 0,
        "offsetY": 256,
        "widthInFrame": 32,
        "heightInFrame": 32,
    }
}